In [19]:
# 1. Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

numbers = [10, 20, 30, 40, 50]
print("Original List:", numbers)

# append()
numbers.append(60)
print("After append:", numbers)

# extend()
numbers.extend([70, 80])
print("After extend:", numbers)

# insert()
numbers.insert(2, 25)
print("After insert:", numbers)

# remove()
numbers.remove(40)
print("After remove:", numbers)

# pop()
removed_element = numbers.pop()
print("After pop:", numbers)
print("Popped element:", removed_element)

# index()
print("Index of 30:", numbers.index(30))

# count()
numbers.append(20)
print("Count of 20:", numbers.count(20))

# sort()
numbers.sort()
print("After sort:", numbers)

# reverse()
numbers.reverse()
print("After reverse:", numbers)

# clear()
numbers.clear()
print("After clear:", numbers)

Original List: [10, 20, 30, 40, 50]
After append: [10, 20, 30, 40, 50, 60]
After extend: [10, 20, 30, 40, 50, 60, 70, 80]
After insert: [10, 20, 25, 30, 40, 50, 60, 70, 80]
After remove: [10, 20, 25, 30, 50, 60, 70, 80]
After pop: [10, 20, 25, 30, 50, 60, 70]
Popped element: 80
Index of 30: 3
Count of 20: 2
After sort: [10, 20, 20, 25, 30, 50, 60, 70]
After reverse: [70, 60, 50, 30, 25, 20, 20, 10]
After clear: []


In [20]:
#2. Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.
students = ("usha","kalpana","gowtham")
print(students)
#trying to change the second name
students[1]="harshad"
#tuple is immutable datatype,which means their elements cannot changed after creation

('usha', 'kalpana', 'gowtham')


TypeError: 'tuple' object does not support item assignment

In [21]:
#3. Create a set of integers with some duplicate values. Print the set and explain the output.
numbers_set={10,20,10,10,22,20,22,25,42,25,42}
print(numbers_set)


{42, 20, 22, 25, 10}


In [22]:
#4. Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.
employee = {
    "name":"usha",
    "age":21,
    "city":"anantapur"
}
print(employee)
#update age
employee["age"]=22
#add email
employee["email"]="usha@22.com"
print(employee)
    

{'name': 'usha', 'age': 21, 'city': 'anantapur'}
{'name': 'usha', 'age': 22, 'city': 'anantapur', 'email': 'usha@22.com'}


In [3]:
#5Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.
age = 23
if age >= 18:
    print("Eligible for voting")
else:
    print("Not eligible for voting")

Eligible for voting


In [24]:
#6. Given a 'marks' variable, print the grade: - 90 and above: 'A' - 75–89: 'B' - 50–74: 'C' - Below 50: 'Fail'
marks=85
if marks >=90:
    print("Grade:A")
elif marks >=75:
    print("Grade:B")
elif marks >=50:
    print("Grade:C")
else:
    print("Fail")


Grade:B


In [2]:
#Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.
num = 6
if num > 0:
    print("Positive Number")
    if num % 2 == 0:
        print("Even Number")
    else:
        print("Odd Number")
elif num == 0:
    print("Zero")
else:
    print("Negative Number")

Positive Number
Even Number


In [32]:
#8. Create: - A scalar using np.array(5) - A 1D array with values 1 to 5 - A 2D array (2x3) with values from 10 to 60 in steps of 10
import numpy as np
scalar=np.array(5)
print(scalar)
#1d array
scalar=np.array([1,2,3,4,5])
print(scalar)
print(type(scalar))
print(scalar.ndim)
#2d array
num=np.array([[10,20,30],[40,50,60]])
print(num)
print(type(num))
num.ndim


5
[1 2 3 4 5]
<class 'numpy.ndarray'>
1
[[10 20 30]
 [40 50 60]]
<class 'numpy.ndarray'>


2

In [27]:
#9. Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().
import numpy as np
arr = np.random.randint(0,101,size=(4,4))
print(arr)

[[ 10  63 100  62]
 [ 18  39  75   0]
 [ 77  52  37   7]
 [  2  83  85  20]]


In [4]:
#10. Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.
import numpy as np
import pandas as pd
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
df = pd.DataFrame(arr)
df.columns = ["A", "B", "C"]
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


In [1]:
#11Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then: - Use .info(), .describe() - Select 'Name' and 'City' columns - Drop 'City' column - Fill any missing values in 'Salary' column with the mean - Remove any duplicate row




import pandas as pd

data = {
    "Name": ["Usha", "Ravi", "Sita", "Anil", "Priya", "Kiran", "Deepa", "Rahul", "Sneha", "Ravi"],
    "Age": [22, 25, 23, 24, 26, 21, 27, 22, 23, 25],
    "City": ["Hyderabad", "Chennai", "Bangalore", "Delhi", "Mumbai", "Hyderabad", "Pune", "Delhi", "Chennai", "Chennai"],
    "Salary": [30000, 45000, None, 40000, 50000, 35000, 55000, None, 42000, 45000]
}

df = pd.DataFrame(data)

# 1. Display information
print(df.info())

# 2. Display statistics
print(df.describe())

# 3. Select Name and City columns
print(df[["Name", "City"]])

# 4. Drop City column
df = df.drop("City", axis=1)

# 5. Fill missing Salary values with mean
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())

# 6. Remove duplicate rows
df = df.drop_duplicates()

print(df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None
             Age        Salary
count  10.000000      8.000000
mean   23.800000  42750.000000
std     1.932184   7959.720024
min    21.000000  30000.000000
25%    22.250000  38750.000000
50%    23.500000  43500.000000
75%    25.000000  46250.000000
max    27.000000  55000.000000
    Name       City
0   Usha  Hyderabad
1   Ravi    Chennai
2   Sita  Bangalore
3   Anil      Delhi
4  Priya     Mumbai
5  Kiran  Hyderabad
6  Deepa       Pune
7  Rahul      Delhi
8  Sneha    Chennai
9   Ravi    Chennai
    Name  Age   Salary
0   Usha   22  30000.0
1   Ravi   25  45000.0
2   Sita   23  42750.0
3   Anil   24 